use_frameworks!

platform :ios, '10.0'

target 'RLSdk_Example' do
  pod 'RLSdk', :path => '../'

  target 'RLSdk_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
